/**
 * Emits web/src/generated/enums.ts from the generated Prisma client so the
 * browser bundle has the enum members and labels without importing
 * @prisma/client (which cannot run in a browser). Wired into `db:generate`,
 * so it re-runs whenever the Prisma client does. Commit the output.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  ALL_COMPLEXITIES,
  ALL_DATA_STRUCTURES,
  ALL_TECHNIQUES,
  CategoryKind,
  COMPLEXITY_LABEL,
  Difficulty,
} from '../src/types';

const OUT = resolve(__dirname, '../web/src/generated/enums.ts');

function constArray(name: string, type: string, values: string[]): string {
  const list = values.map((v) => `  '${v}',`).join('\n');
  return `export const ${name} = [\n${list}\n] as const;\nexport type ${type} = (typeof ${name})[number];\n`;
}

const out = [
  '// GENERATED by scripts/gen-enums.ts from prisma/schema.prisma — do not edit.',
  '// Regenerate with `npm run gen:enums` (also runs as part of `npm run db:generate`).',
  '',
  constArray('DIFFICULTIES', 'Difficulty', Object.values(Difficulty)),
  constArray('DATA_STRUCTURES', 'DataStructure', ALL_DATA_STRUCTURES),
  constArray('TECHNIQUES', 'AlgorithmicTechnique', ALL_TECHNIQUES),
  constArray('COMPLEXITIES', 'Complexity', ALL_COMPLEXITIES),
  constArray('CATEGORY_KINDS', 'CategoryKind', Object.values(CategoryKind)),
  'export const COMPLEXITY_LABEL: Record<Complexity, string> = {',
  ...ALL_COMPLEXITIES.map((c) => `  ${c}: ${JSON.stringify(COMPLEXITY_LABEL[c])},`),
  '};',
  '',
].join('\n');

writeFileSync(OUT, out);
// eslint-disable-next-line no-console
console.log(`wrote ${OUT}`);
